Tutorial for backend with SQL [16577]
eProsima/vulcanexus pull request #113
Opened 2022-12-19 12:00 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2022-12-21 11:10 UTC, juanlofer-eprosima requested changes

2022-12-21 11:10 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +    :lines: 40-49
Wrong end?

2022-12-21 11:10 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +Then open two more terminals and load the Vulcanexus environment.
```suggestion
Now open two more terminals and load the Vulcanexus environment.
```

2022-12-21 11:10 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +Then, in one of them run a ``talker`` and in the other one a ``listener`` of the ``demo_nodes_cpp`` ROS 2 package, available in the Vulcanexus Desktop distribution.
```suggestion
Then, run a ``talker`` and a ``listener`` of the ``demo_nodes_cpp`` ROS 2 package, available in the Vulcanexus Desktop distribution, in a different terminal each.
```

2022-12-21 11:10 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +You can check also :ref:`this tutorial <tutorials_tools_prometheus>` explaining how to connect an application developed with the *Fast DDS Statistics Backend* to a visualization tool like *Grafana*.
```suggestion
You may also check :ref:`this tutorial <tutorials_tools_prometheus>` explaining how to connect an application developed with the *Fast DDS Statistics Backend* to a visualization tool like *Grafana*.
```

2022-12-21 11:25 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +    :lines: 40-49
Also, typo *CMakeList.txt*

2022-12-21 11:28 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +The application workspace will have the following structure at the end of the project.
NIT: an include folder is also created in the workspace.

2022-12-21 14:58 UTC, jparisu commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +    This SQLite3 is already installed in ROS2 environment.
sure about `the`? Vulcanexus :+1:

2022-12-21 15:01 UTC, jparisu commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +The :code:`timestamp` column is the **key** of the table as it cannot be repeated.
Indeed, it is only for this tutorial. I think the SQL details must be designed by the final user

2022-12-21 15:03 UTC, jparisu commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +The application workspace will have the following structure at the end of the project.
Yes, but it is useles... I add a comment about it in the proper command

2022-12-21 15:11 UTC, jparisu commented on code/monitor_sql_tutorial/src/sql_monitor.cpp
> +    StatisticsData get_publication_throughput_mean()
Latency median and Throughput mean

2022-12-21 15:31 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +.. figure:: /rst/figures/tutorials/tools/sql_monitor_backend/summary.png
Oh sorry, I was referring to image `database.png`.

2022-12-21 15:33 UTC, juanlofer-eprosima commented on docs/rst/tutorials/tools/monitor_sql/monitor_sql.rst
> +    :lines: 40-49
Typo still there.

2022-12-22 06:30 UTC, juanlofer-eprosima approved these changes
LGTM

2022-12-22 09:55 UTC, merged