[16912] Fast DDS introduction section
eProsima/vulcanexus pull request #121
Opened 2023-01-31 14:24 UTC by JLBuenoLopez-eProsima

2023-02-01 19:26 UTC, EduPonz requested changes

2023-02-01 19:26 UTC, EduPonz commented on docs/rst/introduction/introduction.rst
> +However, *Vulcanexus* supports `eProsima's Fast DDS <vulcanexus_fastdds>`_ open source implementation.
```suggestion
However, *Vulcanexus* supports :ref:`eProsima's Fast DDS <vulcanexus_fastdds>` open source implementation.
```

2023-02-01 19:26 UTC, EduPonz commented on docs/rst/introduction/middleware.rst
> +Vulcanexus MiddleWare
```suggestion
Vulcanexus Middleware
```

2023-02-01 19:26 UTC, EduPonz commented on docs/rst/introduction/middleware.rst
> +* **Free and Open Source:** *eProsima Fast DDS*, the internal dependencies (such as *eProsima Fast CDR*) and the external ones (such as the *foonathan* library) are free and open source.
```suggestion
* **Free and Open Source:** Both *eProsima Fast DDS*, its internal dependencies (such as *eProsima Fast CDR*), and its external ones (such as the *foonathan* library), are free and open source.
```

2023-02-01 19:26 UTC, EduPonz commented on docs/rst/introduction/middleware.rst
> +Main Features
I think it'd be neat if we added some links to the already existing Vulcanexus tutorials and docs in some of these bullet points.

2023-02-02 07:51 UTC, JLBuenoLopez-eProsima commented
Suggestions applied. Be aware that a new label has been included in ROS 2 documentation fork (eProsima/ros2_documentation#15) so CI is going to fail until that PR is merged. Then a last commit has to be included in this PR updating the submodule.

2023-02-02 18:51 UTC, EduPonz approved these changes

2023-02-02 18:52 UTC, merged