Vulcanexus Galactic Gamble Documentation
eProsima/vulcanexus pull request #14
Opened 2022-03-23 10:14 UTC by EduPonz

This PR adds documentation for Galactic Gamble

2022-03-25 06:26 UTC, JLBuenoLopez-eProsima requested changes
I would have added this commit (26e9680e764e2514a94577d7c7d2780c8ebb8611) in a different PR. This branch was supposed to be an intermediary branch before merging all the documentation into the `galactic` branch once all unknowns were solved. This is the reason where I would not approve this PR yet because there is still work to do (mark with `TODO`).

Currently the following information is unknown:

* [x] Vulcanexus repository final URL
* [x] Vulcanexux webpage final URL
* [ ] Vulcanexus Galactic Release Date

2022-03-25 06:26 UTC, JLBuenoLopez-eProsima commented on docs/rst/figures/intro/vulcanexus_packages_table.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1920" zoomAndPan="magnify" viewBox="0 0 1440 809.999993" height="1080" preserveAspectRatio="xMidYMid meet" ve
The image says `Statiscs Backend` instead of `Statistics Backend`.

2022-03-25 06:26 UTC, JLBuenoLopez-eProsima commented on docs/index.rst
> +to the users' system architecture.
This is not true right now. Either adding a note stating that the documentation is still under work or I suggest removing this sentence.

Another option is modifying to state what the documentation really details:

```suggestion
The following documentation describes how to install *Vulcanexus* packages, some tutorials to know how to get started, the supported platforms and releases.
```

2022-03-28 05:51 UTC, EduPonz commented
> I would have added this commit ([26e9680](https://github.com/eProsima/vulcanexus/commit/26e9680e764e2514a94577d7c7d2780c8ebb8611)) in a different PR. This branch was supposed to be an intermediary branch before merging all the documentation into the `galactic` branch once all unknowns were solved.

You are completely right! I have removed my commit from here and submitted #15 instead. I've applied your suggestions there.

2022-03-29 13:03 UTC, JLBuenoLopez-eProsima approved these changes
:+1:

2022-03-29 13:03 UTC, merged