Add Image Compression for Video Streaming tutorial
eProsima/vulcanexus pull request #221
Opened 2024-11-07 15:30 UTC by LuciaEchevarria99

2024-11-19 08:24 UTC, Javgilavi requested changes

2024-11-19 08:45 UTC, Javgilavi requested changes

2024-11-19 08:45 UTC, Javgilavi commented on docs/rst/tutorials/core/wifi/image_compression/image_compression.rst
> +
Los otros tutoriales de "Vulcanexus WiFi & Large Data Tutorials" tienen una primera subsection de Have you ever have this problem? y con una "Quick Solution Overview". Este tutorial es el unico que no tiene

2024-11-21 07:02 UTC, LuciaEchevarria99 commented on docs/rst/tutorials/core/wifi/image_compression/image_compression.rst
> +
I've change it to: To achieve this, modify the line in ``publisher_from_video.cpp`` file that specifies the publishing rate.
This should be enough.

2024-11-21 08:50 UTC, Javgilavi approved these changes

2024-11-28 10:11 UTC, merged

2024-11-28 10:26 UTC, LuciaEchevarria99 commented
@mergifyio backport humble