[13494] Galactic Gamble Ubuntu binary installation guide
eProsima/vulcanexus pull request #4
Opened 2022-01-13 11:19 UTC by JLBuenoLopez-eProsima

This PR adds the Ubuntu binary installation guide for Vulcanexus Galactic Gamble.

Built over #3.

WIP: the repository URL has to be defined.

2022-01-17 06:22 UTC, EduPonz requested changes

2022-01-17 06:22 UTC, EduPonz commented on docs/rst/installation/linux_installation.rst
> +Next steps
I miss an uninstalling step

2022-01-17 07:07 UTC, JLBuenoLopez-eProsima commented on docs/rst/installation/linux_installation.rst
> +Debian packages for Vulcanexus Galactic Gamble are currently available for Ubuntu Focal.
I have created the [internal task](https://eprosima.easyredmine.com/issues/13515) under the Vulcanexus documentation parent task.

2022-01-17 08:11 UTC, JLBuenoLopez-eProsima commented
Review suggestions applied. The base branch has been changed to an intermediate branch (the repository URL and the public key must be set first).

2022-01-18 11:46 UTC, EduPonz approved these changes
LGTM

2022-01-18 11:46 UTC, merged