Initial micro-ROS tutorials
eProsima/vulcanexus pull request #42
Opened 2022-07-14 13:07 UTC by pablogs9

2022-07-19 14:10 UTC, Acuadros95 approved these changes

2022-07-27 11:54 UTC, EduPonz requested changes

2022-07-27 11:54 UTC, EduPonz commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +`Raspberry Pi Pico <https://www.raspberrypi.com/products/raspberry-pi-pico/>`_ is the versatile embedded and super low cost solution of **Raspberry Pi for microcontroller environments**. It features
I wouldn't expect "exagerating" adjectives such as `super`

2022-07-27 13:38 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +Build System Components
060d25cdfb32bbb2d3fde535d177158207af8e84

2022-07-27 13:49 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +`Zephyr RTOS <https://docs.zephyrproject.org/>`_ is one of the most relevant RTOSes for embedded systems of the last years. **Supported by the Linux Foundation**, it provides a full featured and laye
345efe1eeb01ea977ff6461af224178d0fff6152

2022-07-27 13:51 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +`Zephyr RTOS <https://docs.zephyrproject.org/>`_ is one of the most relevant RTOSes for embedded systems of the last years. **Supported by the Linux Foundation**, it provides a full featured and laye
b0261f825d115eda82f22e4fda38c64405938508

2022-07-27 13:52 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +`NuttX <https://nuttx.apache.org/>`_ is one of the most complete and mature RTOS available. It is **supported by Apache Foundation** and provides a piece of software with emphasis on standard complia
935c33f3d3959e06238c65a9b9d2dbbbbe668328

2022-07-27 13:53 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +micro-ROS app for NuttX provides an example application environment where the micro-ROS stack is integrated in the NuttX 10 build system and can be ran as a NuttX application with an UART transport.
a50307796e806ed7f57ca425a6dd93f706cf086a

2022-07-27 13:53 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +`Raspberry Pi Pico <https://www.raspberrypi.com/products/raspberry-pi-pico/>`_ is the versatile embedded and super low cost solution of **Raspberry Pi for microcontroller environments**. It features
0da9f37abd79499432ec12ba22303f687b90fe4d

2022-07-27 13:54 UTC, pablogs9 commented on docs/rst/tutorials/micro/introduction/introduction.rst
> +^^^^^^^^^^^^
What does this means?

2022-07-27 13:55 UTC, pablogs9 commented on docs/rst/tutorials/micro/introduction/introduction.rst
> +micro-ROS **layered architecture** abstracts the OS/RTOS with a middleware layer. On top of the middleware, micro-ROS uses the same ROS 2 core layers (RMW, RCL and RCUTILS). With respect to user APIs
22e57010d1dd75e262e08e807cb99afd19836bc3

2022-07-27 13:55 UTC, pablogs9 commented
@EduPonz comments addressed. If this LGTY I'll fix CI

2022-07-27 14:52 UTC, pablogs9 commented on docs/rst/tutorials/micro/introduction/introduction.rst
> +^^^^^^^^^^^^
feb4649b17e9f0872453bfa9af05e522149f642f

2022-07-29 08:37 UTC, EduPonz requested changes

2022-07-29 08:37 UTC, EduPonz commented on docs/rst/tutorials/micro/introduction/introduction.rst
> +    `micro-ROS Agent <https://github.com/micro-ROS/micro-ROS-Agent>`_ is distributed along with `Vulcanexus Micro <https://docs.vulcanexus.org/en/latest/>`_. Check the `installation tutorial <https:/
```suggestion
    `micro-ROS Agent <https://github.com/micro-ROS/micro-ROS-Agent>`_ is distributed along with `Vulcanexus Micro <https://docs.vulcanexus.org/en/latest/>`_.
    Check the `installation tutorial <https://docs.vulcanexus.org/en/latest/rst/installation/linux_binary_installation.html>`_.
```

2022-07-29 08:37 UTC, EduPonz commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +This family of MCUs features a wide range of features based on Arm® Cortex®-M33, M23, and M4 processor cores.
features features

2022-07-29 08:37 UTC, EduPonz commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +The micro-ROS component for Renesas provides a set of tools and instructions to integrate the build and configuration of micro-ROS inside of a Renesas e\ :sup:`2` Studio project.
```suggestion
The micro-ROS component for Renesas provides a set of tools and instructions to integrate the build and configuration of micro-ROS within a Renesas e\ :sup:`2` Studio project.
```

2022-07-29 08:45 UTC, pablogs9 commented on docs/rst/tutorials/micro/build_system_components/build_system_components.rst
> +This family of MCUs features a wide range of features based on Arm® Cortex®-M33, M23, and M4 processor cores.
```suggestion
This family of MCUs provides a wide range of features based on Arm® Cortex®-M33, M23, and M4 processor cores.
```

2022-07-29 08:50 UTC, EduPonz approved these changes

2022-07-29 08:58 UTC, merged