Parameter server tutorial
eProsima/vulcanexus pull request #77
Opened 2022-10-10 09:37 UTC by dcoello-eProsima

Signed-off-by: David Coello Pulido <davidcoello@eprosima.com>

2022-10-10 10:08 UTC, pablogs9 requested changes
In general remove all those paragraphs as bullet point lists

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +The parameter server uses five services and an optional publisher. These need to be taken into account on the rmw-microxrcedds package memory configuration:
```suggestion
The parameter server uses five services and an optional publisher. These need to be taken into account on the `rmw_microxrcedds` package memory configuration:

.. TODO(pgarrido): Add link to memory conf tutorial when ready


```

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +Humble: the variable is ``RCLC_PARAMETER_EXECUTOR_HANDLES_NUMBER`` has been renamed to ``RCLC_EXECUTOR_PARAMETER_SERVER_HANDLES``.
We are supporting only humble, rephrase this paragraph and the previous so we use `RCLC_EXECUTOR_PARAMETER_SERVER_HANDLES`

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +Max name size is controlled by the compile-time option `RCLC_PARAMETER_MAX_STRING_LENGTH`, default value is 50.
```suggestion
The parameter string name size is controlled by the compile-time option ``RCLC_PARAMETER_MAX_STRING_LENGTH``, the default value is 50.
```

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +----------------
We are only supporting humble

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Custom options:
```suggestion
A parameter server can be configured at configuration time, the following options can be adjusted:
```

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +    - notify_changed_over_dds: Publish parameter e  vents to other ROS 2 nodes as well.
```suggestion
    - notify_changed_over_dds: Publish parameter events to other ROS 2 nodes as well.
```

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +    - notify_changed_over_dds: Publish parameter e  vents to other ROS 2 nodes as well.
```suggestion
    - ``notify_changed_over_dds``: Publish parameter e  vents to other ROS 2 nodes as well.
```

This in all elements

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Custom options:
decrease the indent level in all this list

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Low memory mode:
Make this a subsection and explain that we have a low memory mode with the following functionality

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- rclc_add_parameter_constraint_integer
All those with the `` to use code block

2022-10-10 10:08 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +`This constrains will not be applied by the parameter server, leaving values filtering to the user callback`.
This as a note

2022-10-10 10:57 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Request size limited to one parameter on Set, Get, Get types and Describe services.
```suggestion
- Request size limited to one parameter on Set, Get, Get types and Describe operations.
```

2022-10-10 10:57 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Low memory mode: 4160 B
```suggestion
.. note::

    Using low memory mode in a STM32F4 with  7 parameters with ``RCLC_PARAMETER_MAX_STRING_LENGTH =         50`` and ``notify_changed_over_dds = true`` the memory usage drops from 11.7 kB to 4.1 kB.
```

2022-10-10 10:57 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Parameter description Adds a description of a parameter and its constrains, which will be returned on a describe parameter requests:
```suggestion
- Parameter description: Adds a description of a parameter and its constraints, which will be returned on a describe parameter request:
```

2022-10-10 10:57 UTC, pablogs9 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Parameter constraints Informative numeric constraints can be added to int and double parameters, returning this values on describe parameter requests:
```suggestion
- Parameter constraints: Informative numeric constraints that can be added to int and double parameters, returning these values on describe parameter requests:
```

2022-10-10 12:14 UTC, pablogs9 commented
LGTM but, please fix the CI:

```
./rst/tutorials/micro/user_api/user_api_parameter_server.rst:184: D000 Bullet list ends without a blank line; unexpected unindent.
```

2022-10-10 12:14 UTC, pablogs9 commented on docs/rst/spelling_wordlist.txt
> +unexisting
order this alphabetically

2022-10-10 14:02 UTC, Acuadros95 commented on docs/rst/tutorials/micro/user_api/user_api_parameter_server.rst
> +- Read-only parameters: The new API offers a read-only flag. This flag blocks parameter changes from external clients, but allows changes on the server side:
```suggestion
- Read-only parameters: This flag blocks parameter changes from external clients, but allows changes on the server side:
```

2022-10-11 06:56 UTC, Acuadros95 approved these changes

2022-10-11 06:56 UTC, merged