[15950] Tutorial - External Locators
eProsima/vulcanexus pull request #84
Opened 2022-11-08 08:03 UTC by Mario-DL

This PR adds a tutorial for leveraging Fast DDS' external locators feature in Vulcanexus.

Cannot be merged before:

*  eprosima/Fast-DDS#3079
* #86

2022-11-10 07:00 UTC, EduPonz requested changes

2022-11-10 10:10 UTC, Mario-DL commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +    Note that the docker network itself does not create another level of externality in this case, as the containers are bridged with the host network.
I moved it before the XML file description, after the line referring to the example above

`Following the example above ....
.. note:: 
....`

2022-11-10 20:17 UTC, EduPonz requested changes
I'd like to congratulate you on the video!

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +                                            <!--container 1 peer-->
```suggestion
                                            <!-- Container 1 peer-->
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +                                            using External Locators, or not -->
```suggestion
                                            <!--
                                                Local network DDS default multicast to discover
                                                other participants in the same LAN,
                                                using External Locators, or not
                                            -->
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +                .. code-block:: xml
I'd move all the XML files to several resource files (like in #86) and include them with literal include.

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +                                            using External Locators, or not -->
Same as above

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +This section provides with step-by-step instructions for setting up the example scenario described in the previous Background section.
```suggestion
This section provides with step-by-step instructions for setting up the example scenario described in previous sections.
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +Finally, export the environment variable pointing to the Profiles file, source Vulcanexus environment and run the ros2 example nodes.
```suggestion
Finally, export the environment variable pointing to the Profiles.xml file, source Vulcanexus environment and run the ros2 example nodes.
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +                    export FASTRTPS_DEFAULT_PROFILES_FILE=/Profiles.xml #Or the Profiles.xml file location
```suggestion
                    export FASTRTPS_DEFAULT_PROFILES_FILE=/Profiles.xml # Or the Profiles.xml file location
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +                        export FASTRTPS_DEFAULT_PROFILES_FILE=/Profiles.xml #Or the Profiles.xml file location
```suggestion
                        export FASTRTPS_DEFAULT_PROFILES_FILE=/Profiles.xml # Or the Profiles.xml file location
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +A message `Hellow World: [count]` should start printing in the talker's container terminal while both listeners keep receiving it, in their respective container consoles, as follows:
```suggestion
A message `Hello World: [count]` should start printing in the talker's container terminal while both listeners keep receiving it, in their respective container consoles, as follows:
```

2022-11-10 20:17 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +        <source src="../../../../../_static/resources/tutorials/core/deployment/external_locators/external_locators.mp4">
Nitpick, the host 2 listener seems to be receiving data before the host 1 talker sends it

2022-11-10 20:20 UTC, EduPonz commented
I've rebased this on top of #86 again since there I had to add the video as raw HTML instead of through the extension because that was breaking the latex compilation on RTD. I've enabled a [build on this branch](https://docs.vulcanexus.org/en/docs-ext_loc_tutorial/rst/tutorials/core/deployment/external_locators/external_locators.html) so we can see how it looks online before merging.

2022-11-10 20:21 UTC, EduPonz requested changes

2022-11-10 20:21 UTC, EduPonz commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +    <video width=100% height=auto autoplay loop controls>
```suggestion
    <video width=100% height=auto autoplay loop controls muted>
```

2022-11-11 06:25 UTC, Mario-DL commented on docs/rst/tutorials/core/deployment/external_locators/external_locators.rst
> +   :scale: 75%
Thanks !

2022-11-11 08:23 UTC, EduPonz approved these changes
Tentatively approving as the docs look very nice to me. However, I'll not merge it until I can run the tutorial once the following is merged:

*  eprosima/Fast-DDS#3079

2022-11-14 14:57 UTC, EduPonz approved these changes

2022-11-14 14:58 UTC, merged