[16024] Add ROS utilities tutorial
eProsima/vulcanexus pull request #91
Opened 2022-11-22 09:19 UTC by dcoello-eProsima

Signed-off-by: David Coello Pulido <davidcoello@eprosima.com>

2022-11-22 09:21 UTC, dcoello-eProsima commented on docs/rst/tutorials/micro/utilities/utilities.rst
> +- ``micro-ROS`` type initializer based on :ref:`rosidl_typesupport_introspection_c <docs/ros2_documentation/source/Concepts/About-Internal-Interfaces.rst>_`.
How can I link this local file?

2022-11-22 13:17 UTC, pablogs9 requested changes

2022-11-22 14:38 UTC, dcoello-eProsima commented on docs/rst/tutorials/micro/utilities/utilities.rst
> +
where I can find more info about this

2022-11-23 13:39 UTC, pablogs9 commented
Depends on https://github.com/eProsima/vulcanexus/pull/93

Please @Acuadros95 review before Friday 25th nov

2022-11-23 13:51 UTC, Acuadros95 commented
Could we solve this TODOS with this tutorial?:
```rst
`Handling messages memory tutorial <https://micro.ros.org/docs/tutorials/advanced/handling_type_memory>`_

.. TODO(pgarrido): replace this tutorial with the one in vulcanexus when available
.. TODO(acuadros95): Add reference to future "Handling messages memory" tutorial
```

Or will `micro-ROS memory handling` tutorial address this?

2022-11-23 13:53 UTC, pablogs9 commented
@Acuadros95  yes, we can reference it

2022-11-23 13:54 UTC, Acuadros95 commented
@pablogs9 After checking the tutorial, this is more like an API explanation. We should probably address that TODOs on the memory tutorial

2022-11-23 14:24 UTC, pablogs9 commented
@dcoello-eProsima could you address @Acuadros95 comments?

2022-11-24 07:58 UTC, Acuadros95 commented on docs/rst/microros_documentation/user_api/user_api_utilities.rst
> +    A full example can be found on how to use this API can be found `here <https://github.com/micro-ROS/micro_ros_arduino/blob/humble/examples/micro-ros_types_handling/micro-ros_types_handling.ino>`_
Same example given in both sections. Move this to the header of the section.

2022-11-24 07:58 UTC, Acuadros95 commented on docs/rst/microros_documentation/user_api/user_api_utilities.rst
> +
```suggestion
- ``max_string_capacity``: Maximum string capacity to use for message fields.
- ``max_ros2_type_sequence_capacity``: Maximum capacity to use for sequence type msg fields (ie: unbounded arrays and lists) which contain ROS 2 msg types.
- ``max_basic_type_sequence_capacity``: Maximum capacity to use for sequence type msg fields (ie: unbounded arrays and lists) which contain basic types (ie: primitive field types).

.. code-block:: c

    static micro_ros_utilities_memory_conf_t conf = {0};
    // OPTIONALLY this struct can configure the default size of strings, basic sequences and composed sequences
    conf.max_string_capacity = 50;
    conf.max_ros2_type_sequence_capacity = 5;
    conf.max_basic_type_sequence_capacity = 5;

All message members will follow this configuration, unless they have a custom rule assigned to them.

```

Moved repeated sentence.

2022-11-24 07:58 UTC, Acuadros95 commented on docs/rst/microros_documentation/user_api/user_api_utilities.rst
> +Returns the static memory size that will be used for a type.
```suggestion
Returns the static memory size that will be used for a type with a given memory configuration.
```

2022-11-24 07:58 UTC, Acuadros95 commented on docs/rst/microros_documentation/user_api/user_api_utilities.rst
> +    uint8_t my_buffer[1000];
```suggestion
```

Not used in this code snippet

2022-11-24 07:58 UTC, Acuadros95 commented on docs/rst/microros_documentation/user_api/user_api_utilities.rst
> +    control_msgs__msg__JointJog msg;
```suggestion
```

Not used in this code snippet

2022-11-24 07:58 UTC, Acuadros95 commented on docs/rst/microros_documentation/user_api/user_api_utilities.rst
> +    size_t size = strlen(str);
```suggestion 
    size_t size = strlen(str) + 1;  // Add null terminator
```

2022-11-24 10:24 UTC, merged